apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: v98aweaqw-nodejs-gitops
  description: This is GitOps manifest for v98aweaqw-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=v98aweaqw-nodejs
    backstage.io/kubernetes-id: v98aweaqw-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: v98aweaqw-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:v98aweaqw-nodejs
